services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"